<a href="https://colab.research.google.com/github/karandeep1729/Data-Analysis-and-Statistics/blob/main/PandasHandsOn15_04_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a list , tuple and a set with elements 1-10. Convert each of the data types into a Pandas Series. Also a create a seperate list of indexes for the Series

In [ ]:
import pandas as pd

In [ ]:
li = [1,2,3,4,5,6,7,8,9,10]
tup = (1,2,3,4,5,6,7,8,9,10)
se = {1,2,3,4,5,6,7,8,9,10}
indexes = ['A','B','C','D','E','F','G','H','I','J']
print(indexes)
print(li,tup,se)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] (1, 2, 3, 4, 5, 6, 7, 8, 9, 10) {1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

In [ ]:
ser = pd.Series([10,20,30,40,50],index=['I','J','K','L','M'])
ser

I    10
J    20
K    30
L    40
M    50
dtype: int64

In [ ]:
ser_li = pd.Series(li,index=indexes)  #Converting our list into a Series
ser_li

A     1
B     2
C     3
D     4
E     5
F     6
G     7
H     8
I     9
J    10
dtype: int64

In [ ]:
ser_tup = pd.Series(tup,index=indexes)  #Creating a series from a Tuple.
ser_tup

A     1
B     2
C     3
D     4
E     5
F     6
G     7
H     8
I     9
J    10
dtype: int64

In [ ]:
ser_se = pd.Series(se)

TypeError: 'set' type is unordered

In [ ]:
# Can I convert our Set into List
ser_se = pd.Series(list(se),index=indexes)
ser_se

A     1
B     2
C     3
D     4
E     5
F     6
G     7
H     8
I     9
J    10
dtype: int64

Create a dictionary with 5 key value pairs. Convert the dictionary into a Series.

In [ ]:
di = {
    'Name':'Rahul',
    'Age':25,
    'Address':'Jaipur',
    'Qualification':'Engineering',
    'Job':'Data Analyst'
}
ser_di = pd.Series(di)
ser_di
# The keys of the dictionary are used as indexes in a Series.

Name                    Rahul
Age                        25
Address                Jaipur
Qualification     Engineering
Job              Data Analyst
dtype: object

Create a Series store 10 elements convert this series into a list , set , tuple and a dictionary.

In [ ]:
new_series = pd.Series([10,20,30,40,50,60,70,80,90,100])
new_li = list(new_series)
new_tup = tuple(new_series)
new_set = set(new_series)
new_di = dict(new_series)
print(new_li,new_tup,new_set,new_di)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100] (10, 20, 30, 40, 50, 60, 70, 80, 90, 100) {100, 70, 40, 10, 80, 50, 20, 90, 60, 30} {0: np.int64(10), 1: np.int64(20), 2: np.int64(30), 3: np.int64(40), 4: np.int64(50), 5: np.int64(60), 6: np.int64(70), 7: np.int64(80), 8: np.int64(90), 9: np.int64(100)}

In [ ]:
new_di

{0: np.int64(10),
 1: np.int64(20),
 2: np.int64(30),
 3: np.int64(40),
 4: np.int64(50),
 5: np.int64(60),
 6: np.int64(70),
 7: np.int64(80),
 8: np.int64(90),
 9: np.int64(100)}

Create a sample series with 10 numerical elements. Print the first 5 and last 5 rows of the Series. Update the 5th index with the value 200. Update the last element of your series with the value 120. Delete the first element from the Series.

In [ ]:
sample = pd.Series([10,20,30,40,50,60,70,80,90,100])
sample

0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int64

In [ ]:
# Display the first 5 rows
sample.head()

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
# Display the last 5 rows
sample.tail()

5     60
6     70
7     80
8     90
9    100
dtype: int64

In [ ]:
sample[5] = 200 #Updating the 5th index element value.
sample

0     10
1     20
2     30
3     40
4     50
5    200
6     70
7     80
8     90
9    100
dtype: int64

In [ ]:
sample[9] = 120
sample

0     10
1     20
2     30
3     40
4     50
5    200
6     70
7     80
8     90
9    120
dtype: int64

In [ ]:
sample

 0     10
 1     20
 2     30
 3     40
 4     50
 5    200
 6     70
 7     80
 8     90
 9    120
-1    150
dtype: int64

In [ ]:
sample.drop(0,inplace=True)   #inplace=True it will store/update the result in actual Series.

In [ ]:
sample

 1     20
 2     30
 3     40
 4     50
 5    200
 6     70
 7     80
 8     90
 9    120
-1    150
dtype: int64

Create a nested list and dictionary (in dictionary store the values in a list). Store atleast 5 values in them and then convert them into a dataframe

In [ ]:
nested_li = [['Rahul','9th','A','2019'],['Kartik','8th','B','2019'],['Aman','10th','C','2018']]
li_df = pd.DataFrame(nested_li)
li_df # We want our own column names.

        0     1  2     3
0   Rahul   9th  A  2019
1  Kartik   8th  B  2019
2    Aman  10th  C  2018

In [ ]:
li_df = pd.DataFrame(nested_li,columns=['Name','Class','Section','YearOfAdmission'])
li_df

     Name Class Section YearOfAdmission
0   Rahul   9th       A            2019
1  Kartik   8th       B            2019
2    Aman  10th       C            2018

In [ ]:
di = {
    'model_name':['Kushaq','Venue','Tucson','Curve','Polo'],
    'Brand':['Skoda','Hyundai','Hyundai','Tata','Wolksvagon'],
    'Year':[2022,2024,2025,2023,2021],
}
di_df = pd.DataFrame(di)
di_df

  model_name       Brand  Year
0     Kushaq       Skoda  2022
1      Venue     Hyundai  2024
2     Tucson     Hyundai  2025
3      Curve        Tata  2023
4       Polo  Wolksvagon  2021

In [ ]:
di_df.rename(columns={'model_name':'Model'},inplace=True)  # Rename the column.

In [ ]:
di_df

    Model       Brand  Year
0  Kushaq       Skoda  2022
1   Venue     Hyundai  2024
2  Tucson     Hyundai  2025
3   Curve        Tata  2023
4    Polo  Wolksvagon  2021

Select all the rows where year >2023 from the above dataframe.

In [ ]:
di_df[di_df['Year']>2023]

    Model    Brand  Year
1   Venue  Hyundai  2024
2  Tucson  Hyundai  2025

In [ ]:
di_df[(di_df['Brand']=='Hyundai') & (di_df['Year']>2024)]

    Model    Brand  Year
2  Tucson  Hyundai  2025

In [ ]:
# Homework:
# Create a dataframe with 4 columns => Car Model , Brand , Year , Price
# Make sure to add atleast 10 rows.
# You need to select all the rows but only with Car Model and Brand column.
# Select the rows from index 1 till 4 index and columns from brand-price.