<a href="https://colab.research.google.com/github/karandeep1729/Data-Analysis-and-Statistics/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas is a python library which is used to work with datasets
Pandas stand for Panel Data
Python Data Analysis

Small Information -> Data
Larger Information(Thousand and lakhs of records. Records in the form of rows and columns) -> Datasets

In [ ]:
import pandas as pd

In [ ]:
#Series
#Data Frame

In [ ]:
li = [11,22,33,'Kartik','James',56.8,'Python']
print(li)

[11, 22, 33, 'Kartik', 'James', 56.8, 'Python']

In [ ]:
se = pd.Series(li)  #Creating a series with a list using pd.Series() fxn
se
#Object data type means it contains some string values

0        11
1        22
2        33
3    Kartik
4     James
5      56.8
6    Python
dtype: object

In [ ]:
new_se = pd.Series(['Kabir','Maxime','Mahesh','Riya','Karthick'])
new_se

0       Kabir
1      Maxime
2      Mahesh
3        Riya
4    Karthick
dtype: object

## Series contains two things -> First is index -> Second is the value(data elements)

In [ ]:
se

0        11
1        22
2        33
3    Kartik
4     James
5      56.8
6    Python
dtype: object

# Slicing with series

In [ ]:
se[2:5]    #[start index: end_index+1]

2        33
3    Kartik
4     James
dtype: object

# Data Frame

In [ ]:
data = [['Kabir',24],['Akhil',26],['Ashwin',29],['Tanmay',31],['Harsh',22],['Ashwin',29]]

In [ ]:
data

[['Kabir', 24],
 ['Akhil', 26],
 ['Ashwin', 29],
 ['Tanmay', 31],
 ['Harsh', 22],
 ['Ashwin', 29]]

In [ ]:
#Creating a dataframe
details = pd.DataFrame(data)  #pd.DataFrame() fxn is used to create a dataframe in pandas
details      #Here we created a dataframe by using a nested list

        0   1
0   Kabir  24
1   Akhil  26
2  Ashwin  29
3  Tanmay  31
4   Harsh  22

In [ ]:
#Let's name our columns
updated_details = pd.DataFrame(data,columns=['Name','Age'])
updated_details

     Name  Age
0   Kabir   24
1   Akhil   26
2  Ashwin   29
3  Tanmay   31
4   Harsh   22
5  Ashwin   29

In [ ]:
di_data = {
    'Cars':['BMW','KIA','MG','Tata','Nissan','BYD'],
    'Price':['56 Lakhs','23 Lakhs','30 Lakhs','12 Lakhs','15 Lakhs','40 Lakhs'],
    'Model':[2024,2021,2022,2024,2023,2020]

}     #09:01PM

In [ ]:
df = pd.DataFrame(di_data)
df    #Keys became my column name

     Cars     Price  Model
0     BMW  56 Lakhs   2024
1     KIA  23 Lakhs   2021
2      MG  30 Lakhs   2022
3    Tata  12 Lakhs   2024
4  Nissan  15 Lakhs   2023
5     BYD  40 Lakhs   2020

In [ ]:
#I want to access the data
#I want to print all the values at index 3
df.loc[3]      #loc function is used to access your elements ->

Cars         Tata
Price    12 Lakhs
Model        2024
Name: 3, dtype: object

In [ ]:
df.loc[0]

Cars          BMW
Price    56 Lakhs
Model        2024
Name: 0, dtype: object

In [ ]:
df.iloc[2:5]   #iloc is used to access your elements via indexes. Allows us to do
               # slicing operations

     Cars     Price  Model
2      MG  30 Lakhs   2022
3    Tata  12 Lakhs   2024
4  Nissan  15 Lakhs   2023

In [ ]:
df

     Cars     Price  Model
0     BMW  56 Lakhs   2024
1     KIA  23 Lakhs   2021
2      MG  30 Lakhs   2022
3    Tata  12 Lakhs   2024
4  Nissan  15 Lakhs   2023
5     BYD  40 Lakhs   2020

In [ ]:
df.iloc[1:5]    #Fetching the rows

     Cars     Price  Model
1     KIA  23 Lakhs   2021
2      MG  30 Lakhs   2022
3    Tata  12 Lakhs   2024
4  Nissan  15 Lakhs   2023

In [ ]:
df.iloc[1:5,0:2]  #iloc["indexes of rows" , "indexes of columns"]

     Cars     Price
1     KIA  23 Lakhs
2      MG  30 Lakhs
3    Tata  12 Lakhs
4  Nissan  15 Lakhs

In [ ]:
new_data = {
    'Emp_Name':['Kabir','Mahesh','Phanendharnadh','Preethi','Maxime','Varsha'],
    'Emp_ID':[1021,1014,1045,1945,1123,1432],
    'Salary':[34000,45000,54000,39000,76000,59000],
    'Designation':['ML Engineer','Data Analyst','Research Analyst','AI Engineer','SDE','Business Analyst'],
    'Shift_timings':['9-5','10-7','11-8','9-5','12-9','8-4']
}

In [ ]:
emp_details = pd.DataFrame(new_data)
emp_details

         Emp_Name  Emp_ID  Salary       Designation Shift_timings
0           Kabir    1021   34000       ML Engineer           9-5
1          Mahesh    1014   45000      Data Analyst          10-7
2  Phanendharnadh    1045   54000  Research Analyst          11-8
3         Preethi    1945   39000       AI Engineer           9-5
4          Maxime    1123   76000               SDE          12-9
5          Varsha    1432   59000  Business Analyst           8-4

In [ ]:
#I want to access designation
emp_details['Designation']   #Accessing particular column from our dataframe

0         ML Engineer
1        Data Analyst
2    Research Analyst
3         AI Engineer
4                 SDE
5    Business Analyst
Name: Designation, dtype: object

In [ ]:
#loc function is used to access your column and rows by it's name
#iloc function is used to access your data by indexes.

In [ ]:
emp_details

         Emp_Name  Emp_ID  Salary       Designation Shift_timings
0           Kabir    1021   34000       ML Engineer           9-5
1          Mahesh    1014   45000      Data Analyst          10-7
2  Phanendharnadh    1045   54000  Research Analyst          11-8
3         Preethi    1945   39000       AI Engineer           9-5
4          Maxime    1123   76000               SDE          12-9
5          Varsha    1432   59000  Business Analyst           8-4

In [ ]:
emp_details.loc[:, ['Emp_ID','Designation','Shift_timings']]
#When we are not aware of the indexes and we want to access our columns we use loc fxn

   Emp_ID       Designation Shift_timings
0    1021       ML Engineer           9-5
1    1014      Data Analyst          10-7
2    1045  Research Analyst          11-8
3    1945       AI Engineer           9-5
4    1123               SDE          12-9
5    1432  Business Analyst           8-4

In [ ]:
emp_details.iloc[:,:4]  #Here we are accessing our data via indexing.

   Emp_ID  Salary       Designation
0    1021   34000       ML Engineer
1    1014   45000      Data Analyst
2    1045   54000  Research Analyst
3    1945   39000       AI Engineer
4    1123   76000               SDE
5    1432   59000  Business Analyst

In [ ]:
emp_details.iloc[:,2:]

   Salary       Designation Shift_timings
0   34000       ML Engineer           9-5
1   45000      Data Analyst          10-7
2   54000  Research Analyst          11-8
3   39000       AI Engineer           9-5
4   76000               SDE          12-9
5   59000  Business Analyst           8-4

# Reading csv files
## Most Crucial part

In [ ]:
cars_data = pd.read_csv('/content/cars.csv')

In [ ]:
cars_data

      mpg  cylinders cubicinches   hp weightlbs  time-to-60  year     brand
0    14.0          8         350  165      4209          12  1972       US.
1    31.9          4          89   71      1925          14  1980   Europe.
2    17.0          8         302  140      3449          11  1971       US.
3    15.0          8         400  150      3761          10  1971       US.
4    30.5          4          98   63      2051          17  1978       US.
..    ...        ...         ...  ...       ...         ...   ...       ...
256  17.0          8         305  130      3840          15  1980       US.
257  36.1          4          91   60      1800          16  1979    Japan.
258  22.0          6         232  112      2835          15  1983       US.
259  18.0          6         232  100      3288          16  1972       US.
260  22.0          6         250  105      3353          15  1977       US.

[261 rows x 8 columns]

In [ ]:
#Print the first 5 rows of my dataframe
cars_data.head()         #head function is used to print the first 5 rows of dataframe

    mpg  cylinders cubicinches   hp weightlbs  time-to-60  year     brand
0  14.0          8         350  165      4209          12  1972       US.
1  31.9          4          89   71      1925          14  1980   Europe.
2  17.0          8         302  140      3449          11  1971       US.
3  15.0          8         400  150      3761          10  1971       US.
4  30.5          4          98   63      2051          17  1978       US.

In [ ]:
#Print the last 5 rows of my dataframe
cars_data.tail()   #tail fxn is used to fetch last 5 rows of dataframe.

      mpg  cylinders cubicinches   hp weightlbs  time-to-60  year    brand
256  17.0          8         305  130      3840          15  1980      US.
257  36.1          4          91   60      1800          16  1979   Japan.
258  22.0          6         232  112      2835          15  1983      US.
259  18.0          6         232  100      3288          16  1972      US.
260  22.0          6         250  105      3353          15  1977      US.

In [ ]:
cars_data.head(10)      #Fetching the first 10 rows

    mpg  cylinders cubicinches   hp weightlbs  time-to-60  year     brand
0  14.0          8         350  165      4209          12  1972       US.
1  31.9          4          89   71      1925          14  1980   Europe.
2  17.0          8         302  140      3449          11  1971       US.
3  15.0          8         400  150      3761          10  1971       US.
4  30.5          4          98   63      2051          17  1978       US.
5  23.0          8         350  125      3900          17  1980       US.
6  13.0          8         351  158      4363          13  1974       US.
7  14.0          8         440  215      4312           9  1971       US.
8  25.4          5         183   77      3530          20  1980   Europe.
9  37.7          4          89   62      2050          17  1982    Japan.

In [ ]:
cars_data.shape   #to get the number of rows and columns of your dataframe

(261, 8)

In [ ]:
#Now I want to find how many null values are there in my dataset
cars_data.isnull()    #Wherever there will be null value it will show as True

       mpg  cylinders  cubicinches     hp  weightlbs  time-to-60   year  brand
0    False      False        False  False      False       False  False  False
1    False      False        False  False      False       False  False  False
2    False      False        False  False      False       False  False  False
3    False      False        False  False      False       False  False  False
4    False      False        False  False      False       False  False  False
..     ...        ...          ...    ...        ...         ...    ...    ...
256  False      False        False  False      False       False  False  False
257  False      False        False  False      False       False  False  False
258  False      False        False  False      False       False  False  False
259  False      False        False  False      False       False  False  False
260  False      False        False  False      False       False  False  False

[261 rows x 8 columns]

In [ ]:
cars_data.isnull().sum()   #Counting the total number of null values with respect to columns

mpg            0
cylinders      0
cubicinches    0
hp             0
weightlbs      0
time-to-60     0
year           0
brand          0
dtype: int64

In [ ]:
#I want report of this dataset

cars_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   mpg          261 non-null    float64
 1   cylinders    261 non-null    int64
 2   cubicinches  261 non-null    object
 3   hp           261 non-null    int64
 4   weightlbs    261 non-null    object
 5   time-to-60   261 non-null    int64
 6   year         261 non-null    int64
 7   brand        261 non-null    object
dtypes: float64(1), int64(4), object(3)
memory usage: 16.4+ KB